# Generated by Django 5.1 on 2024-08-30 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2024, 8, 30, 6, 25, 52, 493576),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(2024, 8, 30, 6, 25, 52, 493593),
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
