# Generated by Django 5.1 on 2024-08-30 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2024, 8, 30, 6, 29, 4, 993468),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(2024, 8, 30, 6, 29, 4, 993485),
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
